### ISSUE TITLE
Themeable guides.

### ISSUE THREAD

**Issue by whaaaley** [lkcampbell/brackets-ruler#40]
I'd like to theme the properties of the guide with CSS, if possible. Right now it looks like most of the style is being added with JavaScript instead of CSS.

**Comment by lkcampbell** [comment]
@dustindowell22, you can already change the color and the line style via the `brackets-ruler.guidePosition` and `brackets-ruler.guideColor` extension preferences.

What other properties did you wish to change?

**Comment by dustindowell22** [comment]
I guess when I read through the readme I mistook the extension preferences for CSS class names. I'd like to style the color and thickness of the guides with CSS and have them be dependant of the theme and not user preferences. Extension preferences are currently disabled on Mac. I'd also like users who download my themes not have to worry about changing colors to match.

**Comment by lkcampbell** [comment]
Oh yeah, I understand now, a way for Theme Authors and Extension Authors to work together to make sure Extension UI elements show up correctly for different themes. Exposing the CSS class names and documenting them in a README would definitely be the way to go. That would be relevant for my Indent Guides extension as well.

I'll have to think a little bit on how to incorporate that idea while still keeping the Extension Preferences, because not all Theme Authors will provide appropriate CSS classes and end users will still need a way to adjust the styles on their own if that is the case.

But, yeah, that's a really good idea.

FYI, Extension Preferences *should* work fine on all platforms. Do you mean that there is no *user interface* for Preferences yet? Eventually, when we get the Preferences UI, it will be much easier for users to adjust this aspect of extensions.
