### ISSUE TITLE
Why use Rulers ? 

### ISSUE THREAD

**Issue by SheepDomination** [lkcampbell/brackets-ruler#44]
Can someone give me an idea why I would need to use rulers ? :-)

**Comment by lkcampbell** [comment]
Typical scenario is to create 80-column wide formatting for your code so everyone can read it without word wrapping. Sometimes, development teams have very specific code formatting criteria that they need to follow regarding code page width. I also use it to make sure my text files with hard wrapping has an 80-column width as well. But, you are correct, not everyone uses ruler, which is why it's an extension and not in the core code of Brackets.
